# Generated by Django 4.2.2 on 2023-06-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_about_guides'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_secured_score', models.IntegerField(default=0)),
                ('emission_limit_score', models.IntegerField(default=0)),
                ('liquidity_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
            ],
        ),
    ]
