# Generated by Django 4.2.2 on 2023-06-17 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_securityscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityscore',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
