# Generated by Django 4.2.2 on 2023-06-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_securityscore_company_alter_company_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decentralized_score', models.IntegerField(default=0)),
                ('performace_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apy_1yr_score', models.IntegerField(default=0)),
                ('apy_5yr_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('performace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.company')),
            ],
        ),
    ]
