# Generated by Django 4.2.2 on 2023-06-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_team_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='performace',
            new_name='company',
        ),
        migrations.AddField(
            model_name='product',
            name='performace_score',
            field=models.IntegerField(default=0),
        ),
    ]
