# Generated by Django 4.2.2 on 2023-06-17 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_liquidity_emission_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_secured_score', models.IntegerField(default=0)),
                ('emission_limit_score', models.IntegerField(default=0)),
                ('liquidity_score', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='emission',
            name='company',
        ),
        migrations.RemoveField(
            model_name='liquidity',
            name='company',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Emission',
        ),
        migrations.DeleteModel(
            name='Liquidity',
        ),
    ]
