# Generated by Django 4.2.2 on 2023-06-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_productscore_name_remove_securityscore_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='asset_secured_score',
        ),
        migrations.RemoveField(
            model_name='company',
            name='emission_limit_score',
        ),
        migrations.RemoveField(
            model_name='company',
            name='liquidity_score',
        ),
    ]
