# Generated by Django 4.2.2 on 2023-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_productscore_total_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscore',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='securityscore',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamscore',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
