# Generated by Django 4.2.2 on 2023-06-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_productscore_total_score_securityscore_total_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
